.TH HNB SECTION "April 25, 2001"
.SH NAME
hnb \- Hierarchical notebook
.SH SYNOPSIS
.B hnb
[\fIoptions\fP]
[\fIfile\fP]
.SH DESCRIPTION
This manual page documents briefly the \fBhnb\fP hierarchical notebook.

\fBHnb\fP is an ncurses program to organize many kinds of data in one place, for
example addresses, todo lists, ideas, book reviews or to store snippets of
brainstorming, to make a structured packing list or just to take random notes. 
It can export ascii/html/latex/postscript, supports todo checkboxes, checkbox
trees with percentages and searching.

\fBHnb\fP uses a simple ascii file for storing your notes. This file can be
specified on the command line. If not specified, ~/.hnb is loaded (or created
if missing).
.SH OPTIONS
\fBHnb\fP can be invoked with the following options:
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-t, \-\-tutorial
Load the tutorial instead of a database.
.SH SEE ALSO
For more information on the usage of the program, load the tutorial or
press \fBF1\fP in the program.

Hnb homepage: http://hnb.sourceforge.net
.SH AUTHOR
Hnb was written by Øyvind Kolås <pippin@users.sourceforge.net>.

This manual page was written by Andras Bali <drewie@bigfoot.com>,
for the Debian GNU/Linux system (but may be used by others).
