#include <stdlib.h>
#include "node.h"
#include "ui.h"
#include "registry.h"

struct{
	int help_level;
	int view_debug;
	int collapse_mode;
	int tutorial;
	int eleet_mode;
	char rc_file[100];
	char db_file[100];
	char default_db_file[100];
}prefs={
	/*int help_level=*/0,
	/*int view_debug=*/0,
	/*int collapse_mode=*/COLLAPSE_ALL,
	/*int tutorial,*/0,
	/*int eleet_mode=*/0,
	/*char rc_file[100];*/"",
	/*char db_file[100];*/"",
	/*char default_db_file[100];*/""
};

void init_prefs(){
#ifndef WIN32
	sprintf (prefs.rc_file, "%s/.hnbrc", getenv ("HOME"));
	sprintf (prefs.default_db_file, "%s/.hnb", getenv ("HOME"));
#endif
#ifdef WIN32
	sprintf (prefs.rc_file, "C:\\hnb.rc");
	sprintf (prefs.default_db_file, "C:\\hnb_data");	
#endif
}

void load_prefs(){
	reg_load(prefs.rc_file);
	prefs.help_level=reg_get_int("/ui/help level/");
	prefs.view_debug=reg_get_int("/ui/view debug/");
	prefs.collapse_mode=reg_get_int("/ui/collapse mode/");
	prefs.eleet_mode=reg_get_int("/ui/eleet mode/");	
}

void save_prefs(){
	reg_set_int("/ui/help level/",prefs.help_level);
	reg_set_int("/ui/view debug/",prefs.view_debug);
	reg_set_int("/ui/collapse mode/",prefs.collapse_mode);
	reg_set_int("/ui/eleet mode/",prefs.eleet_mode);	
	reg_set("/this file is automatically generated each time hnb quits/");
	reg_save(prefs.rc_file);
	reg_close();
}
