/*
 * file_ascii.c -- generic xml import/export filters for hnb
 *
 * Copyright (C) 2001-2003 Øyvind Kolås <pippin@users.sourceforge.net>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59
 * Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#if HAVE_CONFIG_H
#include <config.h>
#endif

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "xml_tok.h"

#include "cli.h"
#include "tree.h"

#include "file.h"
#include "prefs.h"
#include "query.h"

#define indent(count,char)	{int j;for(j=0;j<count;j++)fprintf(file,char);}

#define transform(a,b) case a:\
						{int j=0;const char * msg=b;\
							while(msg[j])\
								out[outpos++]=msg[j++];\
							out[outpos]=0;\
							inpos++;\
							break;\
						}\

/* converts special chars into entities */
static char *xml_quote (const char *in)
{
	static char out[bufsize + 30];	/* for added tags'n'tabs */
	int inpos = 0;
	int outpos = 0;

	out[0] = 0;

	while (in[inpos]) {
		switch (in[inpos]) {
				transform ('&', "&amp;");
				transform ('<', "&lt;");
				transform ('>', "&gt;");
				transform ('\'', "&apos;");
				transform ('"', "&quot;");
			default:
				out[outpos++] = in[inpos++];
				out[outpos] = 0;
				break;
		}
	}
	return (out);
}



static void opml_export_nodes (FILE * file, Node *node, int level)
{
	while (node) {
		char *data = fixnullstring(node_get (node, TEXT));

		fprintf (file, "\n");
		indent (level, "\t");
		fprintf (file, "<outline");

		fprintf (file, " text=\"%s\" ", xml_quote (data));


		if (node_right (node)) {
			fprintf (file, ">");

			opml_export_nodes (file, node_right (node), level + 1);
			fprintf (file, "\n");
			indent (level, "\t");
			fprintf (file, "</outline>");
		} else {
			fprintf (file, "/>");
		}

		node = node_down (node);
	}
}

static int export_opml (char *params, void *data)
{
	Node *node = (Node *) data;
	char *filename = params;
	FILE *file;

	while (*params && (*params != ' '))
		params++;
	if (*params == ' ') {
		*params = 0;
		params++;
	}

	if(!strcmp(filename,"*"))filename=query;
	if (!strcmp (filename, "-"))
		file = stdout;
	else
		file = fopen (filename, "w");

	if (!file) {
		cli_outfunf ("opml export, unable to open \"%s\"", filename);
		return (int) node;
	}

	fprintf (file, "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!--pos:%s-->\n\
<!-- generated by hnb %s (http://hnb.sourceforge.net/) -->\n\
<opml version=\"1.0\">\n\
	<head>\n\
		<title>outline exported from hnb</title>\n\
		<dateCreated></dateCreated>\n\
		<dateModified></dateModified>\n\
		<ownerName></ownerName>\n\
		<ownerEmail></ownerEmail>\n\
		<expansionState></expansionState>\n\
		<vertScrollState></vertScrollState>\n\
		<windowTop>20</windowTop>\n\
		<windowLeft>20</windowLeft>\n\
		<windowBottom>200</windowBottom>\n\
		<windowRight>200</windowRight>\n\
		</head>\n\
	<body>\n", params,
			 VERSION);

	opml_export_nodes (file, node, 0);

	fprintf (file, "\n</body>\n</opml>\n");
	if (file != stdout)
		fclose (file);

	cli_outfunf ("opml export, wrote data to \"%s\"", filename);

	return (int) node;
}

static void xml_unquote(char *str){
	while(*str){
		if(*str=='&' && *(str+1)){
			if (!strncmp ((str+1), "amp",3)) {
				*str='&';
				memmove(str+1,str+5,strlen(str+5)+1);
			} else if (!strncmp ((str+1), "gt",2)) {
				*str='>';
				memmove(str+1,str+4,strlen(str+4)+1);
			} else if (!strncmp ((str+1), "lt",2)) {
				*str='<';
				memmove(str+1,str+4,strlen(str+4)+1);
			} else if (!strncmp ((str+1), "quot",4)) {
				*str='"';
				memmove(str+1,str+6,strlen(str+6)+1);
			} else if (!strncmp ((str+1), "apos",4)) {
				*str='\'';
				memmove(str+1,str+6,strlen(str+6)+1);
			} else {
				/* unhandled entity,.. might as well do a standard html and xml transform?,.. or ? */
			}
		}
		str++;
	}
}

static int import_opml (char *params, void *data)
{
	Node *node = (Node *) data;
	char *filename = params;
	char *rdata;
	int type;
	int in_body = 0;
	int in_outlineelement =0;
	int level = -1;
	xml_tok_state *s;
	import_state_t ist;

	FILE *file;

	if(!strcmp(filename,"*"))filename=query;
	file = fopen (filename, "r");
	if (!file) {
		cli_outfunf ("opml import, unable to open \"%s\"", filename);
		return (int) node;
	}
	s = xml_tok_init (file);
	init_import (&ist, node);

	while (((type = xml_tok_get (s, &rdata)) != t_eof) && (type != t_error)) {
		if (type == t_error) {
			cli_outfunf ("opml import error, parsing og '%s', %s",filename, rdata);
			fclose (file);
			return (int) node;
		}
		if (in_body) {
			if (type == t_tag && !strcmp (rdata, "outline")) {
				level++;
				in_outlineelement=1;
				continue;
			}
			if(in_outlineelement && type == t_att && !strcmp(rdata,"text")){
				xml_tok_get(s,&rdata);
				xml_unquote(rdata);
				import_node_text(&ist,level,rdata);
				continue;
			}
			if ((type == t_endtag || type == t_closeemptytag) && !strcmp(rdata,"outline") ) {
				in_outlineelement=0;
			}
			if ((type == t_closetag || type== t_closeemptytag) && !strcmp (rdata, "outline")) {
				level--;
				continue;
			}
		} else {
			if (type == t_tag && !strcmp (rdata, "body"))
				in_body = 1;
		}
	}

	if (node_getflag (node, F_temp))
		node = node_remove (node);	/* remove temporary node, if tree was empty */

	cli_outfunf ("opml import - imported \"%s\"", filename);
	xml_tok_cleanup(s);
	return (int) node;
}


/*
!init_file_opml();
*/
void init_file_opml(){
	cli_add_command ("export_opml", export_opml, "<filename>");
	cli_add_command ("import_opml", import_opml, "<filename>");
}
