/*
 * prefs.c -- loading, keeping and saving of preferences
 *
 * Copyright (C) 2001,2001 Øyvind Kolås <pippin@users.sourceforge.net>
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59
 * Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
#define PREFS_C

#include <stdlib.h>
#include "node.h"
#include "ui.h"
#include "registry.h"
#include "prefs.h"

struct{
	int help_level;
	int view_debug;
	int collapse_mode;
	int tutorial;
	int eleet_mode;
	int format;
	int def_format;
	char rc_file[100];
	char db_file[100];
	char default_db_file[100];
}prefs={
	/*int help_level=*/0,
	/*int view_debug=*/0,
	/*int collapse_mode=*/COLLAPSE_ALL,
	/*int tutorial,*/0,
	/*int eleet_mode=*/0,
	/*int format*/FORMAT_XML,
	/*int def_format*/FORMAT_XML,
	/*char rc_file[100];*/"",
	/*char db_file[100];*/"",
	/*char default_db_file[100];*/""
};

void init_prefs(){
#ifndef WIN32
	sprintf (prefs.rc_file, "%s/.hnbrc", getenv ("HOME"));
	sprintf (prefs.default_db_file, "%s/.hnb", getenv ("HOME"));
#endif
#ifdef WIN32
	sprintf (prefs.rc_file, "C:\\hnb.rc");
	sprintf (prefs.default_db_file, "C:\\hnb_data");	
#endif
}

void load_prefs(){
	reg_load(prefs.rc_file);
	prefs.help_level=reg_get_int("/ui/help level/");
	prefs.view_debug=reg_get_int("/ui/view debug/");
	prefs.collapse_mode=reg_get_int("/ui/collapse mode/");
	prefs.eleet_mode=reg_get_int("/ui/eleet mode/");
	prefs.def_format=reg_get_int("/file/default_format/");
}

void save_prefs(){
	reg_set_int("/ui/help level/",prefs.help_level);
	reg_set_int("/ui/view debug/",prefs.view_debug);
	reg_set_int("/ui/collapse mode/",prefs.collapse_mode);
	reg_set_int("/ui/eleet mode/",prefs.eleet_mode);
	reg_set_int("/file/default_format/",prefs.def_format);
	reg_set("/this file is automatically generated each time hnb quits/");
	reg_save(prefs.rc_file);
	reg_close();
}
